name: build release

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5.0.2
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: 1.22
        # Path to the go.mod or go.work file.
        go-version-file: ./server/go.mod
    - name: build go
      run: go mod tidy && go mod download
    - name: run .sh file
      run: ./build_release.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mayfly-go-win
        path: .
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
