name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build front Docker image
      run: docker build . --file mayfly_go_web/Dockerfile --tag mayfly-go-web:v1.8.5
    - name: export front image 
      run: docker save -o mayfly-go-web.tar mayfly-go-web:v1.8.5
    - name: Upload front artifact
      uses: actions/upload-artifact@v4
      with:
        name: mayfly-go-web
        path: ./mayfly-go-web.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Build backend Docker image
      run: docker build . --file Dockerfile --tag mayfly-go:v1.8.5
    - name: export backend image 
      run: docker save -o mayfly-go.tar mayfly-go:v1.8.5
    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: mayfly-go
        path: ./mayfly-go.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
